[project]
name = "research-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tksgtkm", email = "h9cd342fd7jgx36@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jax[cuda12]>=0.10.2",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.11.2",
]

[project.scripts]
research-project = "research_project:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
